// Module included in the following assemblies:
//
// * networking/multiple-networks/configuring-sr-iov.adoc

[id="nw-sriov-topology-manager_{context}"]
= Creating NUMA aligned SR-IOV pod

You can create NUMA aligned SR-IOV pod by restricting SR-IOV and CPU resources be allocated from the same NUMA node with `restricted` or `single-numa-node` Topology Manager polices.

.Prerequisites

* Install the OpenShift Command-line Interface (CLI), commonly known as `oc`.
* Refer to [link] for how to enable LatencySensitive profile and configure policies of CPU Manager and Topology Manager. Topology Manager requires CPU Manager policy be configured to `static`.

.Procedure

. Create the following SR-IOV pod spec, and then save the YAML in the `<name>-sriov-pod.yaml` file. Replace `<name>` with a name for this pod.
+
The following example shows a SR-IOV pod spec:

[source,yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: <name> <1>
spec:
  containers:
  - name: sample-container
    image: <image> <2>
    command: ["sleep", "infinity"]
    resources:
      limits:
        memory: "1Gi" <3>
        cpu: "2" <4>
      requests:
        memory: "1Gi"
        cpu: "2"
----
<1> Replace `<name>` with the name of SR-IOV network attachment definition CR.
<2> Replace `<image>` with the name of `sample-pod` image.
<3> Create SR-IOV pod with guaranteed QoS, `memory limits` equals to `memory requests`.
<4> Create SR-IOV pod with guaranteed QoS, `cpu limits` equals to `cpu requests`.

. Create the sample SR-IOV pod by running the following command:
+
----
$ oc create -f <filename> <1>
----
<1>  Replace `<filename>` with the name of the file you created in the previous step.

[NOTE]
=====

=====

. Optional: Confirm that `sample-pod` is configured with guaranteed QoS.
+
----
oc describe pod sample-pod
----

. Optional: Confirm that `sample-pod` is allocated with exclusive CPUs.
+
----
oc exec sample-pod -- cat /sys/fs/cgroup/cpuset/cpuset.cpus
----

. Optional: Confirm that SR-IOV device and CPUs allocated for `sample-pod` are on the same NUMA node.
+
----
oc exec sample-pod -- cat /sys/fs/cgroup/cpuset/cpuset.cpus
----
